### PR TITLE
VS2013 update

### PR DESCRIPTION
**Pull request by vorou**

### CODE REVIEW

**Comment by cromwellryan** [comment]
Looks good.  Thanks for the other two commits as well.  Will get this published on the gallery and placed in releases by End of Week.  You're good for now?

@jcreamer898 I'm going to merge this one in - thanks for the PR though!

**Comment by jcreamer898** [comment]
No problem! I'll go ahead and close mine.

**Comment by vorou** [comment]
oh, sorry, clicked the "Close" button by mistake.

**Comment by cromwellryan** [comment]
@vorou I'm going to merge this.  Is there any chance you can send me a vsix to publish on the gallery?  Sorry, I don't have a VS instance any more :frowning:

**Comment by vorou** [comment]
@billmoling I tried to open the project and got the same error, but that was only due to the absence of VS 2013 SDK (I didn't install it after last OS reinstall). So, I installed it (from [here](http://www.microsoft.com/en-us/download/details.aspx?id=40758)), and I'm able to open the project now.

**Pull request merged**
